### ISSUE TITLE
Floating points are awesome!

### ISSUE THREAD

**Issue by remiolsen** [NationalGenomicsInfrastructure/NGI_dashboards#25]
Try this in javascript:

``` javascript
0.58 * 100
```

The result:
![screen shot 2016-01-27 at 17 14 00](https://cloud.githubusercontent.com/assets/6576325/12619875/4411da72-c51a-11e5-96f7-e7676b91630b.png)

**Comment by Galithil** [comment]
``` javascript
Math.round(0.58*100);
```

or 

``` javascript
(0.58*100).toFixed(0);
```

Also, python : 

``` python
>>> 0.58*100
57.99999999999999
```

**Comment by ewels** [comment]
Easier than that in this case - offending number is in a HighCharts label which supports [string formatting](http://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting). So just a case of changing `{y}` to `{y:,.0f}`. Already done and about to commit.
