### ISSUE TITLE
Deliver data like it's 2016

### ISSUE THREAD

**Issue by remiolsen** [NationalGenomicsInfrastructure/NGI_dashboards#46]
Look at this external dashboard:

![screen shot 2017-01-11 at 14 27 56](https://cloud.githubusercontent.com/assets/6576325/21853423/59d04fb8-d817-11e6-9155-7b31807c2ef9.png)

Makes sense, we don't have any delivered projects with queue date in 2017 yet. I don't know if this is a bug or feature.

**Comment by ewels** [comment]
Fixed as now doing last six months..

**Comment by ewels** [comment]
(and yes - it was pulling in the most recent year's stats and there were no stats for 2017 yet).
